# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildJob1
    steps:
    - bash: echo BuildJob1 Step1
    - bash: echo $(PipelineLevelVariable)
  - job: BuildJob2
    steps:
    - bash: echo BuildJob2 Step1
    - bash: echo BuildJob2 Step2
- stage: DevDeploy
  dependsOn: Build
  variables:
    environment: Dev 
  jobs:
  - job: DevDeployJob1
    steps:
    - bash: echo $(environment)DeployJob1 Step1
- stage: QADeploy
  dependsOn: Build
  variables:
    environment: QA
  jobs:
  - job: QADeployJob1
    variables:
      jobNo: Job2
    steps:
    - bash: echo $(environment)DeployJob1 Step1 for $(jobNo)
- stage: ProdDeploy
  dependsOn:
  - DevDeploy
  - QADeploy
  variables:
    environment: Prod
  jobs:
  - job: ProdDeployJob1
    steps:
    - bash: echo $(environment)DeployJob1 Step1

