# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildJob1
    steps:
    - bash: echo BuildJob1 Step1
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId) 
    - bash: echo $(Build.SourceBranchName) 
    - bash: echo $(Build.SourcesDirectory) 
    - bash: echo $(System.DefaultWorkingDirectory) 
    - bash: ls -R $(System.DefaultWorkingDirectory) 
    - bash: echo $(System.ArtifactStagingDirectory)
    - bash: java -version 
    - bash: node --version
    - bash: ls -R $(System.ArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/*.yml'
        TargetFolder: '$(Build.ArtifactStagingDirectory)' 
    - bash: ls -R $(System.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
